### ISSUE TITLE
I wan to change server port from 3000 to 3001

### ISSUE THREAD

**Issue by ghost** [aayush301/Knowledge-bytes#1]
Hello sir i want to change 3000 port of server to 3001 how will i do that

**Comment by aayush301** [comment]
Hey @sw9919108601 , to run vite server on custom port, you can modify the [dev](https://github.com/aayush301/stackoverflow-clone/blob/main/frontend/package.json#L6) script to run on custom port as follows:
```
"dev": "vite --host  --port 3001",
```
