### ISSUE TITLE
Username and password not accepted  error 535 5.7.8

### ISSUE THREAD

**Issue by ghost** [aayush301/Knowledge-bytes#2]
![IMG_20240317_120611](https://github.com/aayush301/stackoverflow-clone/assets/134361687/786244b6-add8-497e-be2c-a552b71f8774)
UseUsername and password not accepted whi this occured help me please

**Comment by aayush301** [comment]
It seems that you have not provided correct credentials. Can you just double check if username and password both are correct?

**Comment by ghost** [comment]
Will you help me  so tha i can solve this issue please i  firs the email I am using in project, I tested that email in smtp test tool on port 465 with secure ssl and then used that email in project 
But getting error all time  what wrong am I doing.....

**Comment by aayush301** [comment]
Not sure what the problem could be as I have not much come around the issues around the mail service email. Can you try finding the solution online or maybe you can skip this mail service part in this project?
