### ISSUE TITLE
What may be the id and password

### ISSUE THREAD

**Issue by ghost** [aayush301/Knowledge-bytes#3]
I am using simple  email id and  and google app password for that , am I going wrong, then what will be the email and password how will i configure them to use 
How will i configure them with smtp server 

Please help me to get......... 

Please

**Comment by aayush301** [comment]
I am sorry but I have never used SMTP server before. If your question seems to be generic enough, could you try posting your question in stackoverflow?

**Comment by ghost** [comment]
I mean an  option  is used in mail.js file for node mailer
May I use simple Google email id there?

**Comment by aayushgoel301** [comment]
Yes, simple google email should work I suppose.

**Comment by aayushgoel301** [comment]
Simple google email id should work.
